// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import fs from "node:fs";
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

const envs = [".env.production.local", ".env.development.local"]; // production first
if (process.env.NODE_ENV === "development") envs.reverse();

config({
  path: envs
    .map((f) => path.resolve(process.cwd(), f))
    .filter((f) => fs.existsSync(f)),
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
